version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  spring-boot-app:
    build:
      context: .
    ports:
      - 8083:8083
    depends_on:
      - mongodb




